# Generated by Django 4.1.1 on 2022-09-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='release',
            new_name='release_date',
        ),
    ]
